const sessions = new Map();

// In-memory session store:
// - keyed by sessionId (generated by the browser and sent with requests)
// - currently stores uploaded file metadata so later prompts can attach the same files
//
// NOTE: This resets when the backend restarts. For persistence, replace this with
// Redis/SQLite/Postgres and store the Gemini file "name"/"uri" values there.
function ensureSession(sessionId) {
  const normalizedSessionId = String(sessionId || "default-session");

  if (!sessions.has(normalizedSessionId)) {
    sessions.set(normalizedSessionId, {
      files: []
    });
  }

  return sessions.get(normalizedSessionId);
}

function addFiles(sessionId, files) {
  const session = ensureSession(sessionId);
  session.files.push(...files);
  return session.files;
}

function getFiles(sessionId, fileIds = []) {
  const session = ensureSession(sessionId);

  if (!Array.isArray(fileIds) || fileIds.length === 0) {
    return session.files;
  }

  const wanted = new Set(fileIds);
  return session.files.filter((file) => wanted.has(file.id));
}

function removeFile(sessionId, fileId) {
  const session = ensureSession(sessionId);
  const removedFile = session.files.find((file) => file.id === fileId) || null;
  session.files = session.files.filter((file) => file.id !== fileId);
  return {
    removedFile,
    files: session.files
  };
}

function listFiles(sessionId) {
  return ensureSession(sessionId).files;
}

module.exports = {
  addFiles,
  ensureSession,
  getFiles,
  listFiles,
  removeFile
};
